spring:
  datasource:
    url: jdbc:mysql://localhost:3306/networkdb?useSSL=false&serverTimezone=UTC&useSSL=false
    username: root
    password: MariaMal007ElenaMal007Natali98++
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463
